version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_empenhos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha  # Defina uma senha segura
      POSTGRES_DB: db_empenhos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: